### PR TITLE
Added support of getting username from different LDAP attributes in HTTP header.

### PR DESCRIPTION
**Pull request by cryomi**
Hi, folks, refering to https://github.com/chauth/confluence_http_authenticator/issues/52 I did PR. Could you verify my changes, beacuse I am not Java developer.

### CODE REVIEW

**Comment by vladimir-mencl-eresearch** [comment]
Hi, 

Sorry, but this looks like it would break everyone else's use case...

If I'm reading the code correctly, it would replace existing assignment of the (first) value of the remote header to `remoteUser` and instead would filter the values with the assumption this is a parsed DN and would extract all CN Values - and use the first CN value found.

The code would discard all items in values that don't match the "^CN=" - and would break the usage for everyone else.

I'd suggest to rewrite this patch to:
* do this filtering only conditionally based on a config file entry (and default to no filtering)
* make the actual filter configurable (so that it's not tied to CN and could perhaps also use UID.
For example, this could be a new config option:
```
username.filter=^CN=
```
This might perhaps be extended to make the pattern define a capturing group and use the match of the capturing group as the result (and not the whole value) - to strip the "CN=" part out of the username.  So e.g.:
```
username.filter=^CN=(.*)
```

On the code style, I'd avoid redefining the `values` variable to hide the original one - either re-assign to the same variable, or define a new one, but do not hiding an existing variable of the same name.

Thanks for your contribution.

Cheers,
Vlad

**Comment by cryomi** [comment]
Hi folks, I updated PR to pay notes from @vladimir-mencl-eresearch. It still should be verified, I am not Java developer.

**Comment by gmkll** [comment]
Reading the changes, the default is the "old" mechanism, which is ok. If the new strategy "1" is set, the first regex group is set as `remoteUser`.  This requires `username.filter` is set, which is currently `^CN=`  (may be better `^CN=(.*)`?) and a non empty group is found (may better check group is not empty).

Technical note: Reusing the already existing mechanism for regular matchings in `GroupMapper.process` seems here to be unnecessarily complex indeed.

Might merge this soon into trunk/master and may release it then?

**Comment by cryomi** [comment]
@gmkll updated default value to `^CN=(.*)`, technical note is not plain to me, I am not Java developer.

**Comment by gmkll** [comment]
You may provide the config from `RemoteUserAuthenticator` with `StringUtil.getCNMatches(values, config.getUsernameRegexFilter());` changing getCNMatches to 

```java
public static List getCNMatches(List<String> list, String usernameRegexFilter) {
        Pattern p = Pattern.compile(usernameRegexFilter);
```

and add missing imports in StringUtil `import java.util.regex.Matcher;
import java.util.regex.Pattern;`. I also would suggest this:

```java
            String tmpResult = m.group(0);
            if (m.matches() && tmpResult != null && !tmpResult.equals("") ) {
                matches.add(tmpResult);
            }
```
Then the fallback is the default again.

**Comment by cryomi** [comment]
@gmkll, changes you mention are performed.

**Pull request merged**
